In [2]:
import numpy as np

In [4]:
vectorA = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(vectorA) # horizontal
print(vectorA.T) # TRANSPOSE -vertical

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
vactorA = np.arange(0,10)
print(vectorA)
vactorA = np.arange(0,30,2)
print(vactorA)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [25]:
vactorA = np.linspace(0,5,10) # Starting from 0 to 5, give me 10 equal parts
print(vactorA)
print(vectorA.reshape(1,9))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[1 2 3 4 5 6 7 8 9]]


In [5]:
vactorA = np.zeros([5,3])
print(vectorA)
vactorA = np.ones([5,3])
print(vectorA)
vectorA = np.eye(5)
print(vectorA)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
vector1 = np.arange(0,10)
vector2 = np.arange(0,10)
print('---vector---\n vectorA \n',vector1 ,'\n vectorB\n',vector2,'------')
print('---vector addition---\n',(vector1+vector2),'------')
print('---vector multiplication---\n',vector1*vector2,'------')
print('---vector division---\n',1/vector1,'------')
print('---vector sqrt---\n',np.sqrt(vector1),'------')
print('---vector mutual-multiplication---\n',np.matmul(vector1,vector2),'------')

---vector---
 vectorA 
 [0 1 2 3 4 5 6 7 8 9] 
 vectorB
 [0 1 2 3 4 5 6 7 8 9] ------
---vector addition---
 [ 0  2  4  6  8 10 12 14 16 18] ------
---vector multiplication---
 [ 0  1  4  9 16 25 36 49 64 81] ------
---vector division---
 [       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111] ------
---vector sqrt---
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] ------
---vector mutual-multiplication---
 285 ------


In [26]:
vectorColor = np.array(['red',1,2,3,'red',1,2,3,'blue','black','pink','blue'])
print(np.unique(vectorColor))

['1' '2' '3' 'black' 'blue' 'pink' 'red']
