In [2]:
import numpy as np

In [60]:
vectorA = np.array ([[1,2,3],[4,5,6],[7,8,9]])
print(vectorA) # horizontal
print(vectorA[1])
print(vectorA.T) # TRANSPOSE -vertical

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [61]:
vactorA = np.arange(0,10)
print(vectorA,'\n0th element=\n',vectorA[0],'\nElement 0:1=\n',vectorA[0:2])
# vactorA = np.arange(0,30,2)
print(vactorA,'\n',vactorA[np.arange(0,1,5)]) # Question

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
0th element=
 [1 2 3] 
Element 0:1=
 [[1 2 3]
 [4 5 6]]
[0 1 2 3 4 5 6 7 8 9] 
 [0]


In [41]:
vactorA = np.linspace(0,5,10) # Starting from 0 to 5, give me 10 equal parts
print(vactorA)
print(vectorA.reshape(1,9))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]
[[1 2 3 4 5 6 7 8 9]]


In [59]:
vactorA = np.zeros([5,3])
print(vectorA)
vactorA = np.ones([5,3])
print(vectorA)
vectorA = np.eye(5)
print(vectorA)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
vector1 = np.arange(0,10)
vector2 = np.arange(0,10)
print('---vector---\n vectorA \n',vector1 ,'\n vectorB\n',vector2,'------')
print('---vector addition---\n',(vector1+vector2),'------')
print('---vector multiplication---\n',vector1*vector2,'------')
print('---vector division---\n',1/vector1,'------')
print('---vector sqrt---\n',np.sqrt(vector1),'------')
print('---vector mutual-multiplication---\n',np.matmul(vector1,vector2),'------') # Question

---vector---
 vectorA 
 [0 1 2 3 4 5 6 7 8 9] 
 vectorB
 [0 1 2 3 4 5 6 7 8 9] ------
---vector addition---
 [ 0  2  4  6  8 10 12 14 16 18] ------
---vector multiplication---
 [ 0  1  4  9 16 25 36 49 64 81] ------
---vector division---
 [       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111] ------
---vector sqrt---
 [0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] ------
---vector mutual-multiplication---
 285 ------


In [27]:
vectorColor = np.array(['red',1,2,3,'rEd',1,2,3,'Blue','black','pink','blue'])
print(np.unique(vectorColor))

['1' '2' '3' 'Blue' 'black' 'blue' 'pink' 'rEd' 'red']


In [28]:
uniformRandomSamples = np.random.rand(5,5)
standardRandomSamples = np.random.randn(5,5)
print('---Random Variables---\n uniformRandomSamples \n',uniformRandomSamples ,'\n standardRandomSamples\n',standardRandomSamples,'------')


---Random Variables---
 uniformRandomSamples 
 [[0.12686709 0.24804372 0.20876652 0.51027694 0.74845018]
 [0.21092188 0.31682707 0.84443771 0.39541074 0.80277039]
 [0.47763408 0.37162785 0.78817343 0.85908491 0.01549653]
 [0.72288632 0.01959985 0.86778719 0.6067957  0.46605894]
 [0.22493122 0.32570817 0.57682472 0.29481424 0.03526682]] 
 standardRandomSamples
 [[-0.42869955  1.68432145 -2.19551989 -0.26044136  0.27332362]
 [ 0.96636984  0.73235216  1.22049571 -1.95919513  0.41942256]
 [ 1.26632257  0.9225325  -0.18652501 -0.11546404  0.35920106]
 [-0.05512461 -0.78198477  0.50351657  1.77202777  1.06293586]
 [ 1.54397835  0.39131473  0.23271975  0.51938161  0.82189056]] ------


In [38]:
print('---Statistics Operation---\n Mean =',np.mean(uniformRandomSamples),
'\n Standard Daviation=',np.std(uniformRandomSamples),
'\n Min=',np.min(uniformRandomSamples),
'\n Max=',np.max(uniformRandomSamples),'\n------')

---Statistics Operation---
 Mean = 0.442618487782219 
 Standard Daviation= 0.2733075931111982 
 Min= 0.015496534364560555 
 Max= 0.8677871864832831 
------


In [74]:
rand_vec = np.random.rand(19)
print(rand_vec)
rand_vec[3:5]=7
print(rand_vec)
rand_vec[3:5]=[8,8]
print(rand_vec)

[0.81773847 0.91614911 0.15280825 0.35861907 0.03075205 0.33798197
 0.75833598 0.54846143 0.07459221 0.65171235 0.99762001 0.47589237
 0.78647707 0.73197307 0.04257735 0.68082629 0.96072033 0.29673887
 0.47169791]
[0.81773847 0.91614911 0.15280825 7.         7.         0.33798197
 0.75833598 0.54846143 0.07459221 0.65171235 0.99762001 0.47589237
 0.78647707 0.73197307 0.04257735 0.68082629 0.96072033 0.29673887
 0.47169791]
[0.81773847 0.91614911 0.15280825 8.         8.         0.33798197
 0.75833598 0.54846143 0.07459221 0.65171235 0.99762001 0.47589237
 0.78647707 0.73197307 0.04257735 0.68082629 0.96072033 0.29673887
 0.47169791]


In [100]:
rand_vec = np.random.randn(15)
print(rand_vec>0,'\n',rand_vec[rand_vec>0])

[ True  True  True  True  True False False False False False  True  True
  True False False] 
 [0.63191033 1.41786713 0.71627713 0.44926147 0.10243671 0.37013107
 1.18264966 2.15736263]


In [109]:
np.save('week_02_numpy',rand_vec)
np.savez('week_02_numpy',rand_vec,rand_vec1,rand_vec2)
np.savetxt('week_02_numpy.txt',vector1,delimiter=',')
load_vec = np.load('week_02_numpy.npy')
load_vecZip = np.load('week_02_numpy.npz')
load_vecText = np.loadtxt('week_02_numpy.txt',delimiter=',')
print(load_vec,'\n','\n',load_vecText)

[ 0.63191033  1.41786713  0.71627713  0.44926147  0.10243671 -0.39926313
 -0.72575087 -0.16982995 -0.30084814 -0.47935427  0.37013107  1.18264966
  2.15736263 -0.72418677 -0.70320359] 
 
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
