In [1]:
import numpy as np   
import pandas as pd
import os

import seaborn as sns
import matplotlib.pyplot as plt   
import matplotlib.style
plt.style.use('classic')

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("US_Heart_Patients.csv")
df.head()

Gender   age  education  currentSmoker  cigsPerDay  BP Meds  \
0    Male  39.0        4.0            0.0         0.0      0.0   
1  Female  46.0        2.0            0.0         0.0      0.0   
2    Male  48.0        1.0            1.0        20.0      0.0   
3  Female  61.0        3.0            1.0        30.0      0.0   
4  Female  46.0        3.0            1.0        23.0      0.0   

   prevalentStroke  prevalentHyp  diabetes  tot cholesterol  Systolic BP  \
0              0.0           0.0       0.0            195.0        106.0   
1              0.0           0.0       0.0            250.0        121.0   
2              0.0           0.0       0.0            245.0        127.5   
3              0.0           1.0       0.0            225.0        150.0   
4              0.0           0.0       0.0            285.0        130.0   

   Diastolic BP    BMI  heartRate  glucose  Heart-Att  
0          70.0  26.97       80.0     77.0          0  
1          81.0  28.73       95.0     76.0          0  
2          80.0  25.34       75.0     70.0          0  
3          95.0  28.58       65.0    103.0          1  
4          84.0  23.10       85.0     85.0          0

In [3]:
cat=["education","currentSmoker","BP Meds","prevalentStroke","prevalentHyp","diabetes"]
for i in cat:
    df[i]=df[i].astype("object")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Gender           4232 non-null   object 
 1   age              4238 non-null   float64
 2   education        4130 non-null   object 
 3   currentSmoker    4237 non-null   object 
 4   cigsPerDay       4209 non-null   float64
 5   BP Meds          4180 non-null   object 
 6   prevalentStroke  4231 non-null   object 
 7   prevalentHyp     4238 non-null   object 
 8   diabetes         4238 non-null   object 
 9   tot cholesterol  4180 non-null   float64
 10  Systolic BP      4236 non-null   float64
 11  Diastolic BP     4235 non-null   float64
 12  BMI              4216 non-null   float64
 13  heartRate        4236 non-null   float64
 14  glucose          3849 non-null   float64
 15  Heart-Att        4240 non-null   int64  
dtypes: float64(8), int64(1), object(7)
memory usage: 530.1+ KB


In [5]:
cat=[]
num=[]
for i in df.columns:
    if df[i].dtype=="object":
        cat.append(i)
    else:
        num.append(i)
print(cat) 
print(num)

['Gender', 'education', 'currentSmoker', 'BP Meds', 'prevalentStroke', 'prevalentHyp', 'diabetes']
['age', 'cigsPerDay', 'tot cholesterol', 'Systolic BP', 'Diastolic BP', 'BMI', 'heartRate', 'glucose', 'Heart-Att']


In [6]:
df.rename(columns = {"BP Meds": "BPMeds",
                     "tot cholesterol": "tot_cholesterol",
                     "Systolic BP":"Systolic_BP",
                     "Diastolic BP":"Diastolic_BP"},inplace=True)

In [7]:
df.head()

Gender   age education currentSmoker  cigsPerDay BPMeds prevalentStroke  \
0    Male  39.0         4             0         0.0      0               0   
1  Female  46.0         2             0         0.0      0               0   
2    Male  48.0         1             1        20.0      0               0   
3  Female  61.0         3             1        30.0      0               0   
4  Female  46.0         3             1        23.0      0               0   

  prevalentHyp diabetes  tot_cholesterol  Systolic_BP  Diastolic_BP    BMI  \
0            0        0            195.0        106.0          70.0  26.97   
1            0        0            250.0        121.0          81.0  28.73   
2            0        0            245.0        127.5          80.0  25.34   
3            1        0            225.0        150.0          95.0  28.58   
4            0        0            285.0        130.0          84.0  23.10   

   heartRate  glucose  Heart-Att  
0       80.0     77.0          0  
1       95.0     76.0          0  
2       75.0     70.0          0  
3       65.0    103.0          1  
4       85.0     85.0          0

In [8]:
df['Gender'] = np.where(df["Gender"] == "Male",0,
                        (np.where(df["Gender"] == "Female",1,np.nan)))

In [9]:
df['Gender'].value_counts()

1.0    2414
0.0    1818
Name: Gender, dtype: int64

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Gender           4232 non-null   float64
 1   age              4238 non-null   float64
 2   education        4130 non-null   object 
 3   currentSmoker    4237 non-null   object 
 4   cigsPerDay       4209 non-null   float64
 5   BPMeds           4180 non-null   object 
 6   prevalentStroke  4231 non-null   object 
 7   prevalentHyp     4238 non-null   object 
 8   diabetes         4238 non-null   object 
 9   tot_cholesterol  4180 non-null   float64
 10  Systolic_BP      4236 non-null   float64
 11  Diastolic_BP     4235 non-null   float64
 12  BMI              4216 non-null   float64
 13  heartRate        4236 non-null   float64
 14  glucose          3849 non-null   float64
 15  Heart-Att        4240 non-null   int64  
dtypes: float64(9), int64(1), object(6)
memory usage: 530.1+ KB


In [11]:
df.head()

Gender   age education currentSmoker  cigsPerDay BPMeds prevalentStroke  \
0     0.0  39.0         4             0         0.0      0               0   
1     1.0  46.0         2             0         0.0      0               0   
2     0.0  48.0         1             1        20.0      0               0   
3     1.0  61.0         3             1        30.0      0               0   
4     1.0  46.0         3             1        23.0      0               0   

  prevalentHyp diabetes  tot_cholesterol  Systolic_BP  Diastolic_BP    BMI  \
0            0        0            195.0        106.0          70.0  26.97   
1            0        0            250.0        121.0          81.0  28.73   
2            0        0            245.0        127.5          80.0  25.34   
3            1        0            225.0        150.0          95.0  28.58   
4            0        0            285.0        130.0          84.0  23.10   

   heartRate  glucose  Heart-Att  
0       80.0     77.0          0  
1       95.0     76.0          0  
2       75.0     70.0          0  
3       65.0    103.0          1  
4       85.0     85.0          0

In [12]:
from sklearn.impute import KNNImputer
knn_imp = KNNImputer(n_neighbors=1)

In [13]:
# Copy all the predictor variables into X dataframe
X = df.drop('Heart-Att', axis=1)

# Copy target into the y dataframe.  
y = df['Heart-Att']

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25 , 
                                                    random_state=1,
                                                    stratify=y)

In [18]:
X_train = pd.DataFrame(knn_imp.fit_transform(X_train),columns=X_train.columns)

In [19]:
X_train['education'].value_counts()

1.0    1311
2.0     962
3.0     543
4.0     364
Name: education, dtype: int64

In [20]:
X_test = pd.DataFrame(knn_imp.transform(X_test),columns=X_test.columns)

In [21]:
X_test['education'].value_counts()

1.0    451
2.0    326
3.0    163
4.0    120
Name: education, dtype: int64

In [23]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1060 entries, 0 to 1059
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Gender           1060 non-null   float64
 1   age              1060 non-null   float64
 2   education        1060 non-null   float64
 3   currentSmoker    1060 non-null   float64
 4   cigsPerDay       1060 non-null   float64
 5   BPMeds           1060 non-null   float64
 6   prevalentStroke  1060 non-null   float64
 7   prevalentHyp     1060 non-null   float64
 8   diabetes         1060 non-null   float64
 9   tot_cholesterol  1060 non-null   float64
 10  Systolic_BP      1060 non-null   float64
 11  Diastolic_BP     1060 non-null   float64
 12  BMI              1060 non-null   float64
 13  heartRate        1060 non-null   float64
 14  glucose          1060 non-null   float64
dtypes: float64(15)
memory usage: 124.3 KB


In [24]:
cat=["education","currentSmoker","BPMeds","prevalentStroke","prevalentHyp","diabetes",
    "Gender"]
for i in cat:
    X_train[i]=X_train[i].astype("object")

In [25]:
cat=["education","currentSmoker","BPMeds","prevalentStroke","prevalentHyp","diabetes",
    "Gender"]
for i in cat:
    X_test[i]=X_test[i].astype("object")

In [26]:
from sklearn.ensemble import GradientBoostingClassifier
gbcl = GradientBoostingClassifier(random_state=1)
gbcl = gbcl.fit(X_train, y_train)

In [27]:
## Performance Matrix on train data set
from sklearn import metrics
y_train_predict = gbcl.predict(X_train)
model_score = gbcl.score(X_train, y_train)
print(model_score)
print(metrics.confusion_matrix(y_train, y_train_predict))
print(metrics.classification_report(y_train, y_train_predict))

0.8786163522012579
[[2693    4]
 [ 382  101]]
              precision    recall  f1-score   support

           0       0.88      1.00      0.93      2697
           1       0.96      0.21      0.34       483

    accuracy                           0.88      3180
   macro avg       0.92      0.60      0.64      3180
weighted avg       0.89      0.88      0.84      3180



In [28]:
## Performance Matrix on test data set
y_test_predict = gbcl.predict(X_test)
model_score = gbcl.score(X_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_test_predict))
print(metrics.classification_report(y_test, y_test_predict))

0.8415094339622642
[[875  24]
 [144  17]]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91       899
           1       0.41      0.11      0.17       161

    accuracy                           0.84      1060
   macro avg       0.64      0.54      0.54      1060
weighted avg       0.79      0.84      0.80      1060



In [29]:
cat=["education","currentSmoker","BPMeds","prevalentStroke","prevalentHyp","diabetes",
    "Gender"]
for i in cat:
    X_train[i]=X_train[i].astype("int")

In [30]:
for i in cat:
    X_test[i]=X_test[i].astype("int")

In [27]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3180 entries, 0 to 3179
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Gender           3180 non-null   int32  
 1   age              3180 non-null   float64
 2   education        3180 non-null   int32  
 3   currentSmoker    3180 non-null   int32  
 4   cigsPerDay       3180 non-null   float64
 5   BPMeds           3180 non-null   int32  
 6   prevalentStroke  3180 non-null   int32  
 7   prevalentHyp     3180 non-null   int32  
 8   diabetes         3180 non-null   int32  
 9   tot_cholesterol  3180 non-null   float64
 10  Systolic_BP      3180 non-null   float64
 11  Diastolic_BP     3180 non-null   float64
 12  BMI              3180 non-null   float64
 13  heartRate        3180 non-null   float64
 14  glucose          3180 non-null   float64
dtypes: float64(8), int32(7)
memory usage: 285.8 KB


In [31]:
from xgboost import XGBClassifier
XGB_Model = XGBClassifier(n_estimators=100,
                          num_parallel_tree=20,
                          max_depth=2,
                          subsample=0.7,
                          colsample_bytree=0.7)
XGB_Model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.7, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=2,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=20, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=0.7,
              tree_method=None, validate_parameters=False, verbosity=None)

In [32]:
from sklearn import metrics
y_train_predict = XGB_Model.predict(X_train)
model_score = XGB_Model.score(X_train, y_train)
print(model_score)
print(metrics.confusion_matrix(y_train, y_train_predict))
print(metrics.classification_report(y_train, y_train_predict))

0.8761006289308176
[[2688    9]
 [ 385   98]]
              precision    recall  f1-score   support

           0       0.87      1.00      0.93      2697
           1       0.92      0.20      0.33       483

    accuracy                           0.88      3180
   macro avg       0.90      0.60      0.63      3180
weighted avg       0.88      0.88      0.84      3180



In [33]:
## Performance Matrix on test data set
y_test_predict = XGB_Model.predict(X_test)
model_score = XGB_Model.score(X_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_test_predict))
print(metrics.classification_report(y_test, y_test_predict))

0.8452830188679246
[[877  22]
 [142  19]]
              precision    recall  f1-score   support

           0       0.86      0.98      0.91       899
           1       0.46      0.12      0.19       161

    accuracy                           0.85      1060
   macro avg       0.66      0.55      0.55      1060
weighted avg       0.80      0.85      0.80      1060



In [34]:
pd.DataFrame(XGB_Model.feature_importances_*100,index=X_train.columns)

0
Gender           10.106512
age              12.569566
education         4.865635
currentSmoker     4.676482
cigsPerDay        6.950399
BPMeds            5.591652
prevalentStroke   4.877643
prevalentHyp     10.380495
diabetes          6.140604
tot_cholesterol   4.826037
Systolic_BP       7.716621
Diastolic_BP      5.325624
BMI               5.232696
heartRate         4.609351
glucose           6.130689

In [47]:
X_train.columns

Index(['Gender', 'age', 'education', 'currentSmoker', 'cigsPerDay', 'BPMeds',
       'prevalentStroke', 'prevalentHyp', 'diabetes', 'tot_cholesterol',
       'Systolic_BP', 'Diastolic_BP', 'BMI', 'heartRate', 'glucose'],
      dtype='object')

In [49]:
X_train.head()

Gender   age  education  currentSmoker  cigsPerDay  BPMeds  \
0       1  63.0          2              0         0.0       0   
1       1  57.0          2              1        10.0       0   
2       1  45.0          4              0         0.0       0   
3       1  46.0          3              1        23.0       0   
4       1  51.0          1              1        15.0       0   

   prevalentStroke  prevalentHyp  diabetes  tot_cholesterol  Systolic_BP  \
0                0             0         0            276.0        134.0   
1                0             1         0            238.0        133.0   
2                0             0         0            250.0        116.0   
3                0             0         0            285.0        130.0   
4                0             0         0            352.0        136.5   

   Diastolic_BP    BMI  heartRate  glucose  
0          85.0  23.64       70.0     86.0  
1          72.0  18.09      100.0    115.0  
2          79.0  28.59       93.0     87.0  
3          84.0  23.10       85.0     85.0  
4          87.0  25.79       73.0     67.0

In [37]:
cat_columns = ['Gender', 'education', 'currentSmoker',
               'BPMeds','prevalentStroke', 'prevalentHyp', 'diabetes']

In [35]:
from catboost import CatBoostClassifier
CatBoostClassifier()

In [36]:
from catboost import CatBoostClassifier
CAT_Model = CatBoostClassifier(iterations=50)
CAT_Model.fit(X_train, y_train,
              cat_features=cat_columns,plot=True)

NameError: name 'cat_columns' is not defined

In [55]:
from sklearn import metrics
y_train_predict = CAT_Model.predict(X_train)
model_score = CAT_Model.score(X_train, y_train)
print(model_score)
print(metrics.confusion_matrix(y_train, y_train_predict))
print(metrics.classification_report(y_train, y_train_predict))

0.8981132075471698
[[2698    0]
 [ 324  158]]
              precision    recall  f1-score   support

           0       0.89      1.00      0.94      2698
           1       1.00      0.33      0.49       482

    accuracy                           0.90      3180
   macro avg       0.95      0.66      0.72      3180
weighted avg       0.91      0.90      0.88      3180



In [56]:
y_test_predict = CAT_Model.predict(X_test)
model_score = CAT_Model.score(X_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_test_predict))
print(metrics.classification_report(y_test, y_test_predict))

0.8452830188679246
[[884  14]
 [150  12]]
              precision    recall  f1-score   support

           0       0.85      0.98      0.92       898
           1       0.46      0.07      0.13       162

    accuracy                           0.85      1060
   macro avg       0.66      0.53      0.52      1060
weighted avg       0.79      0.85      0.79      1060



In [58]:
from lightgbm import LGBMClassifier
lgb_model = LGBMClassifier()

In [59]:
lgb_model.fit(X_train, y_train,)

LGBMClassifier()

In [60]:
y_train_predict = lgb_model.predict(X_train)
model_score = lgb_model.score(X_train, y_train)
print(model_score)
print(metrics.confusion_matrix(y_train, y_train_predict))
print(metrics.classification_report(y_train, y_train_predict))

0.9619496855345911
[[2696    2]
 [ 119  363]]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98      2698
           1       0.99      0.75      0.86       482

    accuracy                           0.96      3180
   macro avg       0.98      0.88      0.92      3180
weighted avg       0.96      0.96      0.96      3180



In [61]:
y_test_predict = lgb_model.predict(X_test)
model_score = lgb_model.score(X_test, y_test)
print(model_score)
print(metrics.confusion_matrix(y_test, y_test_predict))
print(metrics.classification_report(y_test, y_test_predict))

0.8424528301886792
[[877  21]
 [146  16]]
              precision    recall  f1-score   support

           0       0.86      0.98      0.91       898
           1       0.43      0.10      0.16       162

    accuracy                           0.84      1060
   macro avg       0.64      0.54      0.54      1060
weighted avg       0.79      0.84      0.80      1060

