# Section 1:  NumPy Solutions

### Import the library with alias np

In [5]:
import numpy as np

####  1. Create an array of  8 eights

In [6]:
data_array1 = np.arange(1,9)
data_array1

array([1, 2, 3, 4, 5, 6, 7, 8])

#### 2. Create an array of the integers from 10 to 50

In [7]:
data_array2 = np.arange(10,51)
data_array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 3. Create a 3x3 matrix with values ranging from 22 to 30

In [6]:
data_matrix1 = np.arange(22,31).reshape(3,3)
data_matrix1

array([[22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

## Indexing
Use below Array 'arr' for Questions below. 

Use Indexing to get the answer

#### 4. Use indexing on arr to get below output

       [[37, 38, 39, 40],
       [42, 43, 44, 45],
       [47, 48, 49, 50]]

ValueError: cannot reshape array of size 14 into shape (3,4)

#### 5. Use indexing on arr to get below output
Output should be 50

#### 6. Use indexing on arr to get below output
      [[27],
       [32],
       [37]]

#### 7. Use indexing on arr to get below output
      [46, 47, 48, 49, 50]

#### 8. Use indexing on arr to get below output
     [[41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]]

### NumPy  Stats Functions

Use below given array 'arr'

#### 9. Find the sum of all the values in given array 'arr'

#### 10. Find the standard deviation of the values in given array 'arr'

#### 11.  Find the mean of all the values in given array 'arr'

# Section 2: Pandas Solutions

#### Import pandas library  with alias pd

In [12]:
import pandas as pd

#### Read the given csv file

In [17]:
data_sales = pd.read_csv('sales.csv')

### 1. What are the unique values in  the column "Parking"?

In [20]:
data_unique_parking = np.unique(data_sales['Parking'])
data_unique_parking

array(['Covered', 'No Parking', 'Not Provided', 'Open'], dtype=object)

### 2. What is the mean store area of the given data? 

In [22]:
data_sales['Store_Area'].mean()

1511.862554112554

### 3.What are the different columns available in the dataset?

In [26]:
data_sales.columns

Index(['Observation', 'Dist_Taxi', 'Dist_Market', 'Dist_Metro', 'Store_Area',
       'Items_Available', 'Parking', 'Coupon_Category', 'Daily_Customer_Count',
       'Store_Sales'],
      dtype='object')

### 4. Create a new series (series1) with only the values of third row

In [36]:
series_row_3 = data_sales[3:4]
series_row_3

Observation  Dist_Taxi  Dist_Market  Dist_Metro  Store_Area  \
3            4     8301.0      11188.0     12289.0      1451.0   

   Items_Available  Parking Coupon_Category  Daily_Customer_Count  Store_Sales  
3           1748.0  Covered           CAT B                   620        53730

### 5. Create a new dataframe(df_short which contain first 5 rows and two columns("Coupon_Category" and "Store_Sales")

In [ ]:
df_short = 

### 6. In dataframe df_short, replace the index with ["First Row","Second Row","Third Row", "Forth Row", "Fifth Row"]

### 7. Create a dataframe df2 fulfilling the given conditions - Dist_Metro>18000 and Parking= Open

### 8.What is the minimum store sales and the standard Deviation of store sales.

### 9. Group the dataset with respect to the variable 'Coupon_Category' using aggregation function mean()

### 10. Drop the variable 'Parking' from the dataset.

### 11. Export the Q6 dataframe without the 'Parking' column into a csv file.

# Question on some additional functions

###  Display the first 10 entries of the dataset.  (Hint-use function head())

###  Display the last 5 entries of the dataset.(Hint- use function tail())

### How many rows and columns are present in the dataset? (Hint- Use function shape)

###  What are the different data types of the variables in the given dataset? (Hint- Use function info())