In [4]:
import numpy as np
import pandas as pd

In [7]:
mylist=[1,2,3.1,4,5]
myarray=np.array(mylist)

In [13]:
myseries1=pd.Series(data=mylist)
myseries2=pd.Series(data=myarray)
mylabels=['first','second','third','forth','fifth']
myseries3=pd.Series(data=mylist,index=mylabels)
print(myseries1,'\n',myseries2,'\n',myseries3)

0    1.0
1    2.0
2    3.1
3    4.0
4    5.0
dtype: float64 
 0    1.0
1    2.0
2    3.1
3    4.0
4    5.0
dtype: float64 
 first     1.0
second    2.0
third     3.1
forth     4.0
fifth     5.0
dtype: float64


In [17]:
myseries4=pd.Series([1,2,3,4,5],['one','two','three','four','five'])
print(myseries3+myseries4)

fifth    NaN
first    NaN
five     NaN
forth    NaN
four     NaN
one      NaN
second   NaN
third    NaN
three    NaN
two      NaN
dtype: float64


In [20]:
df1 = pd.concat([myseries4,myseries3],axis=1,sort=False)
df1

0    1
one     1.0  NaN
two     2.0  NaN
three   3.0  NaN
four    4.0  NaN
five    5.0  NaN
first   NaN  1.0
second  NaN  2.0
third   NaN  3.1
forth   NaN  4.0
fifth   NaN  5.0

In [23]:
df2 = pd.DataFrame(np.random.randn(5,5))
df2

0         1         2         3         4
0  1.818844  0.247649 -0.307451  0.146550  0.762101
1  0.563775  0.417790  0.536830  0.166455  0.652604
2 -0.028378 -0.771922 -0.586059 -0.369446  0.949667
3 -0.734324  0.110766  0.791847  0.012157 -0.394968
4 -1.682466  0.093241  0.939853 -2.146856  0.639860

In [28]:
df3 = pd.DataFrame(np.random.randn(5,5),('1r','2r','3r','4r','5r'),('1c','2c','3c','4c','5c'))
df3
# df3[['1c','3c']]

1c        2c        3c        4c        5c
1r -1.191954  0.928743 -0.722547 -0.630100 -0.377382
2r  2.081956 -0.156313 -0.566144  0.693742 -1.693138
3r -0.826936  1.154003 -1.099493  1.304615  2.567018
4r  0.205647 -1.852375  1.243721  0.620811  0.785214
5r  1.348710 -1.524598 -0.092266  0.427600 -0.411211

In [31]:
df3.loc['1r']

1c   -1.191954
2c    0.928743
3c   -0.722547
4c   -0.630100
5c   -0.377382
Name: 1r, dtype: float64

In [33]:
df3.iloc[2] # 2nd row

1c   -0.826936
2c    1.154003
3c   -1.099493
4c    1.304615
5c    2.567018
Name: 3r, dtype: float64

In [37]:
df3.loc[['1r','3r'],['1c','3c']]

1c        3c
1r -1.191954 -0.722547
3r -0.826936 -1.099493

In [39]:
df3['6c']=np.random.randn(5,1)
df3

1c        2c        3c        4c        5c        6c
1r -1.191954  0.928743 -0.722547 -0.630100 -0.377382  0.172531
2r  2.081956 -0.156313 -0.566144  0.693742 -1.693138 -1.474638
3r -0.826936  1.154003 -1.099493  1.304615  2.567018  0.421047
4r  0.205647 -1.852375  1.243721  0.620811  0.785214 -0.608669
5r  1.348710 -1.524598 -0.092266  0.427600 -0.411211 -0.288188

In [42]:
df4 = df3.drop('1c',axis=1)
df4

2c        3c        4c        5c        6c
1r  0.928743 -0.722547 -0.630100 -0.377382  0.172531
2r -0.156313 -0.566144  0.693742 -1.693138 -1.474638
3r  1.154003 -1.099493  1.304615  2.567018  0.421047
4r -1.852375  1.243721  0.620811  0.785214 -0.608669
5r -1.524598 -0.092266  0.427600 -0.411211 -0.288188

In [46]:
df4.reset_index(inplace=True)
df4

level_0 index        2c        3c        4c        5c        6c
0        0    1r  0.928743 -0.722547 -0.630100 -0.377382  0.172531
1        1    2r -0.156313 -0.566144  0.693742 -1.693138 -1.474638
2        2    3r  1.154003 -1.099493  1.304615  2.567018  0.421047
3        3    4r -1.852375  1.243721  0.620811  0.785214 -0.608669
4        4    5r -1.524598 -0.092266  0.427600 -0.411211 -0.288188

In [55]:
# Combine dataframe combine, join, merge
df7 = pd.DataFrame({
    "customer":[1,2,3,4],
    "category":['cat1','cat2','cat3','cat4'],
    "important":['y','n','n','y'],
    "sales":[124,253,55.54,89] })
df8 = pd.DataFrame({
    "customer":[5,6,7,8],
    "color":['c1','c2','c3','c4'],
    "isnonveg":['y','n','n','y'],
    "sales":[124,253,55.54,89] })
pd.concat([df7,df8],axis=0,sort=True)

category color  customer important isnonveg   sales
0     cat1   NaN         1         y      NaN  124.00
1     cat2   NaN         2         n      NaN  253.00
2     cat3   NaN         3         n      NaN   55.54
3     cat4   NaN         4         y      NaN   89.00
0      NaN    c1         5       NaN        y  124.00
1      NaN    c2         6       NaN        n  253.00
2      NaN    c3         7       NaN        n   55.54
3      NaN    c4         8       NaN        y   89.00

In [56]:
pd.concat([df7,df8],axis=1,sort=True)

customer category important   sales  customer color isnonveg   sales
0         1     cat1         y  124.00         5    c1        y  124.00
1         2     cat2         n  253.00         6    c2        n  253.00
2         3     cat3         n   55.54         7    c3        n   55.54
3         4     cat4         y   89.00         8    c4        y   89.00

In [58]:
pd.concat([df7,df8],axis=0,sort=False)

customer category important   sales color isnonveg
0         1     cat1         y  124.00   NaN      NaN
1         2     cat2         n  253.00   NaN      NaN
2         3     cat3         n   55.54   NaN      NaN
3         4     cat4         y   89.00   NaN      NaN
0         5      NaN       NaN  124.00    c1        y
1         6      NaN       NaN  253.00    c2        n
2         7      NaN       NaN   55.54    c3        n
3         8      NaN       NaN   89.00    c4        y

In [62]:
# pd.merge(df7,df8,how='inner',on='customer')
# pd.merge(df7,df8,how='outer',on='customer')
pd.merge(df7,df8,how='left',on='customer')

customer category important  sales_x color isnonveg  sales_y
0         1     cat1         y   124.00   NaN      NaN      NaN
1         2     cat2         n   253.00   NaN      NaN      NaN
2         3     cat3         n    55.54   NaN      NaN      NaN
3         4     cat4         y    89.00   NaN      NaN      NaN

In [73]:
df9 = pd.DataFrame({
    "Q1":[1,2,3,4],
    "Q2":[124,253,55.54,89]},
    index=['I0','I1','I2','I3'])
df10 = pd.DataFrame({
    "Q3":[5,6,7,8],
    "Q4":[124,253,55.54,89]},
    index=['I5','I6','I7','I8'])
# df9.join(df10,how='outer')
df9
df10 = df10[(df10['Q3']!=5)&(df10['Q3']!=6)]
df10

Q3     Q4
I7   7  55.54
I8   8  89.00

In [74]:
def profit(s):
    return s*0.5

In [76]:
df10['Q4'].apply(profit)

I7    27.77
I8    44.50
Name: Q4, dtype: float64

In [78]:
df10.applymap(profit)

Q3     Q4
I7  3.5  27.77
I8  4.0  44.50

In [80]:
df10.apply(sum)

Q3     15.00
Q4    144.54
dtype: float64

In [85]:
df9.sort_values(by='Q2',inplace=True)
df9

Q1      Q2
I2   3   55.54
I3   4   89.00
I0   1  124.00
I1   2  253.00

In [92]:
mydict = {
    'customer':['1','2','1','2','1','2','1'],
    'product1':[1.1,2.6,2.6,3.2,6.5,2.3,6.9],
    'product1':[21.1,12.6,32.6,13.42,16.45,21.33,16.9],
    'product1':[21.1,32.6,42.46,33.2,76.5,42.43,66.9]
    }
df6 = pd.DataFrame(mydict,index=['p1','p2','p3','p4','p5','p6','p7'])
df6

customer  product1
p1        1     21.10
p2        2     32.60
p3        1     42.46
p4        2     33.20
p5        1     76.50
p6        2     42.43
p7        1     66.90

In [95]:
group_data = df6.groupby('customer')
group_data.describe()

product1                                                         
            count       mean        std   min    25%    50%     75%    max
customer                                                                  
1             4.0  51.740000  24.952029  21.1  37.12  54.68  69.300  76.50
2             3.0  36.076667   5.510321  32.6  32.90  33.20  37.815  42.43

In [97]:
df6.to_csv('week_02_df6.csv',index=True)

In [100]:
new_df6 = pd.read_csv('week_02_df6.csv',index_col=0)
new_df6

customer  product1
p1         1     21.10
p2         2     32.60
p3         1     42.46
p4         2     33.20
p5         1     76.50
p6         2     42.43
p7         1     66.90

In [112]:
demo_array=np.arange(0,10)
# demo_array
# demo_array <3
# demo_array[demo_array <6]
# np.max(demo_array)

9

In [114]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[:, (1,2)]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [116]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[2,3]

39

In [124]:
demo_array = np.arange(10,21)
subset_demo_array = demo_array[0:7]
subset_demo_array[:]= 101
subset_demo_array

array([101, 101, 101, 101, 101, 101, 101])

In [123]:
test_array = [10, 11.5, 12, 13.5, 14,15]
test_array[2:3]

[12]

In [126]:
np.arange(0,22,6)

array([ 0,  6, 12, 18])

In [128]:
list_l =[[12,34,55,],[66,45,77],[45,77,88]]
np.array(list_l)

array([[12, 34, 55],
       [66, 45, 77],
       [45, 77, 88]])

In [130]:
score = [10, 15, 20, 25]
pd.Series(data=score, index = ['a','b','c','d'])

a    10
b    15
c    20
d    25
dtype: int64

In [135]:
data = {'prodID': ['101', '102', '103', '104', '104'],

                    'prodname': ['X', 'Y', 'Z', 'X', 'W'],

                     'profit': ['2738', '2727', '3497', '7347', '3743']}

dataframe = pd.DataFrame(data)

dataframe

grouped_data = dataframe.groupby('prodID')

grouped_data.max()

prodname profit
prodID                
101           X   2738
102           Y   2727
103           Z   3497
104           X   7347

In [137]:
vec=np.arange(10,20,3)
print(vec)

[10 13 16 19]


In [139]:
vec=np.linspace(10,20,3)
print(vec)

[10. 15. 20.]


In [141]:
vec1=np.arange(0,12)
vec2=vec1.reshape(4,3)
print (vec2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [143]:
vec= np.array([4,7,8,9,10,6,1])
print(vec[vec>6])

[ 7  8  9 10]


In [145]:
vec1= np.array([4,7,8,9,10,6,1])
vec1[vec1>6]=2
print(vec1)

[4 2 2 2 2 6 1]
